version: '2.4'

services:
    discovery-service:
        build: ./superheroback/discovery-service
        ports:
            - "8761:8761"  
      
    hero-service:
        build: ./superheroback/hero-service
        environment:
            - REGISTRY_HOST=discovery-service
            - SUPER_HERO_API_ACCESS_TOKEN=4255357494489968
        ports:
            - "8090:8090" 
        depends_on:
            - discovery-service
            
    api-gateway:
        build: ./superheroback/api-gateway
        environment:
            - REGISTRY_HOST=discovery-service
        ports:
            - "8080:8080"
        depends_on:
            - discovery-service
            - hero-service
    super-hero-front:
        build: ./superherofront
        ports:
          - '8000:8000'
        depends_on:
          - hero-service
          - api-gateway